version: '2.2'

services:
    pwn:
        build: ./
        volumes: 
            - ./share:/home/pwn:ro 
            - ./xinetd:/etc/xinetd.d/xinetd:ro
            - ./tmp:/tmp:ro
        ports:
            - "60001:8888"
        expose:
            - "8888"
        pids_limit: 1024
        cpus: 0.5
        restart: unless-stopped
        
networks:
    default:
        external:
            name: pwn

