version: '3.3'

services:
  mysql:
    build: ./mysql
    container_name: TetCTFTokenDatabase
    command: --default-authentication-plugin=mysql_native_password --sql_mode=""
    restart: always
    environment:
     - MYSQL_ROOT_PASSWORD=#####CENSORED#####
     - MYSQL_USER=TetCTFToken
     - MYSQL_PASSWORD=#####CENSORED#####
     - MYSQL_DATABASE=TetCTFToken

    ports:
     - "3306:3306"
  web:
    build: .
    container_name: TetCTFTokenWebService
    volumes:
     - ./TetCTFToken/:/home/TetCTFToken
    ports:
     - "0.0.0.0:31337:31337"
    depends_on:
      - mysql
