[package]
name = "moar-horse"
version = "1.0.0"
edition = "2021"

[features]
no-entrypoint = []

[dependencies]
borsh = "0.9.3"
borsh-derive = "0.9.3"
solana-program = "1.8.14"

[lib]
crate-type = ["cdylib", "lib"]
