# https://github.com/tomowatt/unity-docker-example
version: '3.8'

services:
  webgl:
    container_name: unity-webgl-demo
    image: unity-webgl-demo
    build: .
    ports:
      - "8080:80"