services:
  circuits:
    build: .
    ports:
      - 9068:5000
    cap_drop:
      - all
    cap_add:
      - chown
      - setuid
      - setgid
      - sys_admin
      - mknod
    security_opt:
      - apparmor=unconfined
      - seccomp=unconfined
      - systempaths=unconfined