version: "3"
services:

  chall:
    build:
      dockerfile: Dockerfile
    cap_add:
      - SYS_ADMIN
    security_opt:
      - apparmor:unconfined

    restart: always
    ports:
      - 27499:1024
